### ISSUE TITLE
 missing required parameter "memory".

### ISSUE THREAD

**Issue by dayglo** [ambitioninc/container-transform#13]
Great tool thanks!

Which docker-compose value is the script looking for for the memory value?

I tried mem_limit but no joy:

I get `Container db is missing required parameter "memory".`.

**Comment by micahhausler** [comment]
It is looking for the `mem_limit`, as defined in the [compose docs](https://docs.docker.com/compose/yml/#working95dir-entrypoint-user-hostname-domainname-mem95limit-privileged-restart-stdin95open-tty-cpu95shares) and [docker run](https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory). Can you post the YAML you are trying to convert?

**Comment by micahhausler** [comment]
Also, what version are you running?
```
container-transform --version
```

**Comment by micahhausler** [comment]
I'll close this since there's been no response, I'll re-open if required

**Comment by gdohmeier** [comment]
container-transform, version 1.1.5
Im running into this error too.  I believe it is due to the new docker compose 3 formatting which changes that mem_limit.?

**Comment by gdohmeier** [comment]
i switched to v2 of docker compose file 
 and added     mem_limit: 1500000000  under image: 
worked like a charm.. app likely needs update to transform the v3x compose files
