### ISSUE TITLE
Publish Docker Hub Image

### ISSUE THREAD

**Issue by smazurov** [ambitioninc/container-transform#17]
Hey, first of all, awesome tool, thanks a lot for putting it together.

Second, would you mind publishing it as a docker image? 

My usecase: we have jenkins with slaves that run docker images (all of our apps are dockerized so we run tests inside containers). The slaves can only do 1 thing, run docker. They don't have any other dependancies. 

I want to keep the image that runs the slaves as minimal as I can, so I don't want to install a ton of tooling, but running tools in images is very cheap. I can of course fork and publish it myself, but I figure you want to have control of that image/project. After all, work is yours and is fantastic.

No big rush, as I can just build it once on a slave and then its cached.

**Comment by micahhausler** [comment]
Sure, that is easy enough. It looks like the current Dockerfile is broken. I'll get it up later today.

**Comment by micahhausler** [comment]
```
docker pull ambition/container-transform
```

```
docker run --rm -v $(pwd):/data/ ambition/container-transform  docker-compose.yml
# or
cat docker-compose.yml | docker run --rm -i ambition/container-transform
```

:)

**Comment by smazurov** [comment]
awesome, thanks a bunch!
